name: Go

on:
  push:
    branches: ["stage"]
  pull_request:
    branches: ["stage"]

env:
  REGISTRY: "kozs"
  IMAGE_NAME: "SmartHome"

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: go test -v ./...
  build:
    needs: test
    if: github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          tags: kozs/smarthome:night
  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.1.0
        with:
        # relative path to compose file
        compose-file: ./docker-compose.yaml
        # additional options to pass to `docker-compose down` command
        #down-flags: # optional, default is
        # services to perform docker-compose up
        #services: # optional
        # additional options to pass to `docker-compose up` command
        up-flags: -d
